[build]
  # We add 'npx' before the command to ensure Netlify finds the local tsx tool
  command = "npx tsx script/build.ts"
  publish = "dist/public"

[functions]
  directory = "server"
  external_node_modules = ["lightningcss", "esbuild"]

[build.processing.node_bundle]
  ignored_node_modules = ["vite", "@replit/vite-plugin-cartographer"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200