[build]
  command = "npm run build"
  publish = "dist/public"

[build.processing.node_bundle]
  # We are telling Netlify to skip bundling these problematic files
  ignored_node_modules = ["vite", "@replit/vite-plugin-cartographer"]
  external_node_modules = ["lightningcss", "esbuild"]

[functions]
  directory = "server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200