[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "server"
  # This tells Netlify NOT to try and bundle these specific packages
  external_node_modules = ["lightningcss", "esbuild"]

[build.processing.node_bundle]
  ignored_node_modules = ["vite", "@replit/vite-plugin-cartographer"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200